import { useDidShow } from '@tarojs/taro'
import Taro from '@tarojs/taro'
import { Text, View } from '@tarojs/components'
import { useState } from 'react'
import { AssignmentSummary, clearAuthContext, getEmployeeAssignments, getStoreDashboard, StoreDashboard, syncAuthContext } from '../../../services/api'
import '../common.scss'

const context=()=>({role:Taro.getStorageSync('training:entry-role')||'employee',membership:Taro.getStorageSync('training:membership')||{}})
export default function HomePage(){
  const[{role,membership},setContext]=useState(context());const[dashboard,setDashboard]=useState<StoreDashboard|null>(null);const[tasks,setTasks]=useState<AssignmentSummary[]>([])
  useDidShow(()=>{syncAuthContext().then(next=>{if(!next.membership){clearAuthContext();Taro.reLaunch({url:'/pages/index/index'});return}setContext(next);if(next.role==='manager')getStoreDashboard(next.membership.store_id).then(setDashboard);else getEmployeeAssignments().then(x=>setTasks(x.filter(a=>a.status!=='completed')))}).catch(()=>{clearAuthContext();Taro.reLaunch({url:'/pages/index/index'})})})
  const manager=role==='manager'
  return <View className='main-page'><View className='topline'><View><Text className='kicker'>{manager?'店长工作台':'员工学习中心'}</Text><Text className='page-title'>{manager?'上午好，开始培训':'今天也要认真上岗'}</Text><Text className='page-sub'>{membership.store_name||'尚未选择门店'}</Text></View><Text className='role-pill'>{manager?'店长':'员工'}</Text></View>
    {manager?<><View className='hero-card'><Text className='hero-title'>把门店制度变成可执行的练习</Text><Text className='hero-desc'>生成后先审核原文依据，再发布给员工。</Text></View><View className='actions'><View className='action' onClick={()=>Taro.navigateTo({url:'/pages/index/index?create=1'})}><Text className='action-title'>粘贴生成</Text><Text className='action-desc'>适合短篇 SOP</Text></View><View className='action' onClick={()=>Taro.navigateTo({url:'/pages/upload/index'})}><Text className='action-title'>上传手册</Text><Text className='action-desc'>PDF / DOCX</Text></View></View><Text className='section-title'>门店概览</Text><View className='stats'><View className='stat'><Text className='stat-number'>{dashboard?.course_count||0}</Text><Text className='stat-label'>全部题库</Text></View><View className='stat'><Text className='stat-number'>{dashboard?.draft_count||0}</Text><Text className='stat-label'>待审核</Text></View><View className='stat'><Text className='stat-number'>{dashboard?.pending_assignments||0}</Text><Text className='stat-label'>待完成任务</Text></View><View className='stat'><Text className='stat-number'>{dashboard?.completed_assignments||0}</Text><Text className='stat-label'>已完成</Text></View></View></>:<><View className='hero-card'><Text className='hero-title'>{tasks.length?`还有 ${tasks.length} 项培训待完成`:'今天没有待办培训'}</Text><Text className='hero-desc'>答题结果用于学习复盘，不等同于实操认证。</Text></View><Text className='section-title'>待学习</Text>{tasks.map(task=><View className='list-card' key={task.id} onClick={()=>Taro.navigateTo({url:`/pages/assignment/index?assignmentId=${task.id}`})}><View className='row-head'><Text className='row-title'>{task.title}</Text><Text className='status'>{task.status==='pending'?'待开始':'进行中'}</Text></View><Text className='row-meta'>点击进入岗位练习 →</Text></View>)}{!tasks.length&&<Text className='empty'>暂无待学习任务</Text>}</>}
  </View>}
