-- M4 上岗练多租户模型；生产环境按版本执行，不由应用启动时建表。
CREATE TABLE stores (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, owner_user_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_store_owner(owner_user_id), CONSTRAINT fk_store_owner FOREIGN KEY(owner_user_id) REFERENCES users(id));
CREATE TABLE store_members (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, store_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, role ENUM('owner','manager','employee') NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_store_user(store_id,user_id), KEY idx_member_user(user_id), FOREIGN KEY(store_id) REFERENCES stores(id), FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE documents (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, document_id VARCHAR(64) NOT NULL UNIQUE, store_id BIGINT UNSIGNED NOT NULL, file_name VARCHAR(255) NOT NULL, storage_key VARCHAR(500) NOT NULL, status ENUM('uploaded','parsing','ready','failed') NOT NULL, content_hash CHAR(64) NOT NULL, deleted_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_documents_store(store_id), FOREIGN KEY(store_id) REFERENCES stores(id));
CREATE TABLE document_blocks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, document_id BIGINT UNSIGNED NOT NULL, block_id VARCHAR(64) NOT NULL, page_number INT NULL, paragraph_index INT NOT NULL, text MEDIUMTEXT NOT NULL, start_offset INT NOT NULL, end_offset INT NOT NULL, UNIQUE KEY uk_document_block(document_id,block_id), FOREIGN KEY(document_id) REFERENCES documents(id));
CREATE TABLE training_courses (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, quiz_id VARCHAR(64) NOT NULL UNIQUE, store_id BIGINT UNSIGNED NOT NULL, document_id BIGINT UNSIGNED NULL, title VARCHAR(100) NOT NULL, status ENUM('draft','awaiting_review','approved','published','archived') NOT NULL, prompt_version VARCHAR(50) NOT NULL, graph_version VARCHAR(50) NOT NULL, model_version VARCHAR(100) NOT NULL, reviewer_user_id BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_courses_store(store_id), FOREIGN KEY(store_id) REFERENCES stores(id));
CREATE TABLE training_questions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, course_id BIGINT UNSIGNED NOT NULL, question_id VARCHAR(64) NOT NULL, stem TEXT NOT NULL, answer_json JSON NOT NULL, explanation TEXT NOT NULL, evidence_json JSON NOT NULL, requires_confirmation BOOLEAN NOT NULL DEFAULT FALSE, confirmed_by BIGINT UNSIGNED NULL, UNIQUE KEY uk_course_question(course_id,question_id), FOREIGN KEY(course_id) REFERENCES training_courses(id));
CREATE TABLE question_options (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, question_id BIGINT UNSIGNED NOT NULL, option_key VARCHAR(8) NOT NULL, option_text TEXT NOT NULL, UNIQUE KEY uk_question_option(question_id,option_key), FOREIGN KEY(question_id) REFERENCES training_questions(id));
CREATE TABLE course_publications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, course_id BIGINT UNSIGNED NOT NULL, store_id BIGINT UNSIGNED NOT NULL, published_by BIGINT UNSIGNED NOT NULL, published_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_publication_store(store_id), FOREIGN KEY(course_id) REFERENCES training_courses(id));
CREATE TABLE training_assignments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, store_id BIGINT UNSIGNED NOT NULL, course_id BIGINT UNSIGNED NOT NULL, employee_user_id BIGINT UNSIGNED NOT NULL, status ENUM('pending','in_progress','completed','expired') NOT NULL DEFAULT 'pending', due_at DATETIME NULL, UNIQUE KEY uk_assignment(course_id,employee_user_id), KEY idx_assignment_employee(employee_user_id), FOREIGN KEY(course_id) REFERENCES training_courses(id));
CREATE TABLE answer_attempts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, assignment_id BIGINT UNSIGNED NOT NULL, store_id BIGINT UNSIGNED NOT NULL, employee_user_id BIGINT UNSIGNED NOT NULL, status ENUM('in_progress','completed') NOT NULL, score INT NULL, submitted_at DATETIME NULL, UNIQUE KEY uk_assignment_final(assignment_id,status), FOREIGN KEY(assignment_id) REFERENCES training_assignments(id));
CREATE TABLE training_answer_records (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, attempt_id BIGINT UNSIGNED NOT NULL, question_id BIGINT UNSIGNED NOT NULL, selected_json JSON NOT NULL, is_correct BOOLEAN NOT NULL, duration_ms INT NOT NULL DEFAULT 0, UNIQUE KEY uk_attempt_question(attempt_id,question_id), FOREIGN KEY(attempt_id) REFERENCES answer_attempts(id));
CREATE TABLE training_reports (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, attempt_id BIGINT UNSIGNED NOT NULL UNIQUE, store_id BIGINT UNSIGNED NOT NULL, report_json JSON NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(attempt_id) REFERENCES answer_attempts(id));
CREATE TABLE question_feedback (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, store_id BIGINT UNSIGNED NOT NULL, question_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, value ENUM('accurate','ambiguous','unsupported') NOT NULL, note VARCHAR(500) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_feedback(question_id,user_id));
CREATE TABLE agent_runs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, thread_id VARCHAR(64) NOT NULL UNIQUE, store_id BIGINT UNSIGNED NOT NULL, task_id VARCHAR(64) NOT NULL, status ENUM('pending','running','awaiting_review','completed','failed') NOT NULL, input_length INT NOT NULL, content_hash CHAR(64) NOT NULL, model_version VARCHAR(100) NOT NULL, prompt_version VARCHAR(50) NOT NULL, graph_version VARCHAR(50) NOT NULL, token_usage INT NOT NULL DEFAULT 0, revision_count INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_agent_store(store_id));
CREATE TABLE agent_run_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agent_run_id BIGINT UNSIGNED NOT NULL, node VARCHAR(50) NOT NULL, duration_ms INT NOT NULL, retry_count INT NOT NULL DEFAULT 0, issue_codes_json JSON NULL, error_category VARCHAR(50) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(agent_run_id) REFERENCES agent_runs(id));
CREATE TABLE privacy_requests (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, request_type ENUM('complaint','delete_account','delete_document') NOT NULL, resource_id VARCHAR(64) NULL, detail VARCHAR(1000) NOT NULL DEFAULT '', status ENUM('pending','processing','completed','rejected') NOT NULL DEFAULT 'pending', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_privacy_user(user_id), FOREIGN KEY(user_id) REFERENCES users(id));
